### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by vanessa** [rmmaf/Public-CIn#1]
Primeiramente, parabéns mesmo por estar usando o GitHub e começar o desafio bem antes do prazo! 😉

Teu public tá muito bem estruturado e dividido (inclusive, parabéns por se preocupar em fazê-lo responsivo também - muita gente deixa isso passar batido), vi que você tá aplicando bem certinho o que aprendemos com flexbox. A estrutura tá muito boa, realmente só falta estilizá-lo com fontes, cores e tudo mais. Uma dica que te dou se quiser usar fontes diferentes das que estão instaladas no computador por padrão é usar o [Google Fonts](http://fonts.google.com).

Notei que no footer você usou a propriedade `align-self` e setou uma largura fixa para ele. Não sei se você quer alinhá-lo ao canto direito, mas se quiser apenas centralizar, não precisa usar o `align-self` nem o `width`, é só manter a altura (`height`) e usar a propriedade `margin: 0 auto;` (isso quer dizer quer as margens para cima e para baixo serão 0 e para os lados será automático, o que fará com que o elemento procure se centralizar).

Uma dica de ouro que te dou é usar sempre o recurso Ferramentas de Desenvolvedor do Google Chrome (é aquele console que você consegue ver o código fonte e selecionar os elementos quando você aperta F12). Quando algo não estiver dando certo, não desista, só dá um `Ctrl + Shift + C` e tenta selecionar o que você quer e ir testando propriedades. Por exemplo, pra chegar na resposta anterior, eu saí [desmarcando](https://cloud.githubusercontent.com/assets/23136832/26660348/e46e5a44-464d-11e7-8ccf-0aa3df7e4b8f.png) as propriedades pra ver como seria a melhor forma de colocar o footer.

Essas são minhas observações pra agora, mas posso te ajudar quando tu quiser! Só me mencionar nessa issue ou conversar comigo no Facebook 🙃

**Comment by rmmaf** [comment]
Ótimo, valeu pela dica de centralizar o footer (fiz uma gambiarra meio doida pra fazer isso). Sobre dica de ouro: vou baixar o Chrome (uso Firefox). Valeu pela ajuda :)

**Comment by rmmaf** [comment]
Vanessa, seguinte, estou com duas dúvidas:

1 Como faço para do footer para baixo deixar uma cor diferente do fundo? Tipo, se eu coloco para colorir o footer só colore a linha dele.

2 Esse esquema de modificar a organização do site quando a tela é reduzida, pelo visto não funciona com dispositivos móveis, como faço uma versão mobile? Ou isso será ensinado? 

![photo5008555488253683642](https://cloud.githubusercontent.com/assets/23747884/26705036/cb86ffb0-4709-11e7-9026-3a2288e17252.jpg)

**Comment by vanessa** [comment]
Oi @rmmaf! Respondendo tuas dúvidas:

1. Pelo que vi no seu código, a tag `footer` aparece apenas como o conteúdo (no caso, os ícones das redes sociais) ao invés da linha em si. Pra resolver isso, tu tem que separar o CSS do footer com as imagens dentro dele, fica assim no estilo:
```css
footer {
  margin: 0 auto;
  background: green;
  width: 100%;
  text-align: center;
}

footer img {
  width: 90px;
  margin: 20px;
}
```

2. Isso se dá porque o navegador não sabe que o site é responsivo, então ele carrega como se fosse pra uma única tela. Você tem que usar essa tag `meta` dentro do `head`: 
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by rmmaf** [comment]
Então, essa tua primeira solução não funcionou. Para corrigir eu troquei o "%" por "vw" (dei uma googlada sobre viewport). Ainda não tá como quero (com um footer tão responsivo quanto o do site do CITi, por exemplo), mas melhorou bastante. Eu tentei fazer do zero com 3 containers (um com tudo, um com a parte de cima e outro com o footer) e usando apenas "vw/vh" como medida, mas a página ficou toda quebrada quando dava zoom, aí desisti. E para que o footer ficasse embaixo eu fiz uma gambiarra com a margem do topo.

Sobre a segunda solução: Funcionou! Valeu pela ajuda

Tá aqui o site sobre viewport:
https://developer.mozilla.org/pt-BR/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by vanessa** [comment]
Vê, só pra entender, como o site do CITi significa ele estar colado no final da página ou ele tomar realmente todo o espaço da página? Se for estar colado, eu uso flexbox no body nessa configuração bem básica:
```css
body {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
```
Então o body vira um grande flex-container e eu divido a página assim: menu de navegação (`nav`), o conteúdo do site (o corpo mesmo, tudo) (`section`) e o footer (`footer`).

Se for pra tomar todo o espaço, o que acontece é que a maioria dos navegadores renderizam as páginas com um padding padrão, pra resolver, é só colocar `padding: 0` no body.

**Edit:** Agora que eu li de novo, tenta usar `min-height: 100%` no body.

Já já eu clono e tento mexer.
